### ISSUE TITLE
안녕하세요 데이터셋은 어디서 얻을 수 있나요?

### ISSUE THREAD

**Issue by CVStack** [babjo/TaxiDataApi#1]
안녕하세요 데이터셋은 어디서 얻을 수 있나요?

서울시 열린관장에는 이제 더이상 없는것 같아서요.

혹시 아직 가지고 계신다면 얻을 수 있을까요?

**Comment by babjo** [comment]
안녕하세요. 아쉽지만 오래전 프로젝트라 가지고 있는 데이터는 없습니다.

**Comment by CVStack** [comment]
넵 알겠습니다.
